Installation du venv

diff --git a/usershub/DEBIAN/postinst b/usershub/DEBIAN/postinst
--- a/usershub/DEBIAN/postinst
+++ b/usershub/DEBIAN/postinst
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # postinst script for usershub
 #
 # see: dh_installdeb(1)
@@ -20,51 +20,62 @@ set -o xtrace
 
 . /usr/share/debconf/confmodule
 
-if [ -f /usr/share/debconf/confmodule ]; then
-    db_version 2.0
-    db_input high usershub/URL_APPLICATION || true
-    db_input high usershub/PASS_METHOD || true
-    db_input high usershub/FILL_MD5_PASS || true
-    db_input low usershub/COOKIE_EXPIRATION || true
-    db_input low usershub/ACTIVATE_API || true
-    db_input low usershub/ACTIVATE_APP || true
-    db_input high usershub/SECRET_KEY || true
-    for p in GUN_NUM_WORKERS GUN_HOST GUN_PORT; do
-        db_input high usershub/${p} || true
-    done
-    db_go
-fi
-
-for p in URL_APPLICATION PASS_METHOD FILL_MD5_PASS COOKIE_EXPIRATION ACTIVATE_API ACTIVATE_APP SECRET_KEY; do
-    db_get usershub/${p}
-    export ${p}="$RET"
-done
-
 # Generate config files
-echo "Generate configuration" >&2
-CONF_DIR=/etc/geonature
-for f in "usershub.conf"; do
-    envsubst <$CONF_DIR/$f.init >$CONF_DIR/$f
-done
+function generate_config() {
+    echo "Generate configuration" >&2
+    for p in URL_APPLICATION PASS_METHOD FILL_MD5_PASS COOKIE_EXPIRATION ACTIVATE_API ACTIVATE_APP SECRET_KEY; do
+        db_get usershub/${p}
+        export ${p}="$RET"
+    done
+
+    CONF_DIR=/etc/geonature
+    for f in "usershub.conf"; do
+        envsubst <$CONF_DIR/$f.init >$CONF_DIR/$f
+    done
+}
+
+#  Installation du venv
+function setup_venv() {
+    rm -rf /usr/share/usershub/venv
+    python3 -m venv /usr/share/usershub/venv
+    /usr/share/usershub/venv/bin/pip install -r /usr/share/usershub/requirements.txt
+}
 
 # Reload supervisor
-if [ -f /etc/init.d/supervisor ]; then
-    if which invoke-rc.d >/dev/null; then
-        if invoke-rc.d supervisor status >/dev/null 2>&1; then
-            invoke-rc.d supervisor reload 3>/dev/null || true
-        fi
-    else
-        if /etc/init.d/supervisor status >/dev/null 2>&1; then
-            /etc/init.d/supervisor reload 3>/dev/null || true
+function reload_supervisor() {
+    if [ -f /etc/init.d/supervisor ]; then
+        if which invoke-rc.d >/dev/null; then
+            if invoke-rc.d supervisor status >/dev/null 2>&1; then
+                invoke-rc.d supervisor reload 3>/dev/null || true
+            fi
+        else
+            if /etc/init.d/supervisor status >/dev/null 2>&1; then
+                /etc/init.d/supervisor reload 3>/dev/null || true
+            fi
         fi
     fi
-fi
+}
 
 case "$1" in
 configure)
-
+    generate_config
+    setup_venv
+    reload_supervisor
     echo "configure done"
 
+    ;;
+triggered)
+    for trigger in $2; do
+        case "$trigger" in
+        /usr/bin/python?.*)
+            setup_venv
+            ;;
+        *)
+            #echo >&2 "ERROR:" $(basename "$0") "called with unknown trigger '$2'"
+            #exit 1
+            ;;
+        esac
+    done
     ;;
 
 abort-upgrade | abort-remove | abort-deconfigure) ;;
